# Generated by Django 4.0 on 2021-12-21 03:18

from django.db import migrations, models
import posts.validators


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_post_options_alter_post_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, upload_to='media/postVideo', validators=[posts.validators.video_file_extension]),
        ),
    ]
